### ISSUE TITLE
Errors when running NPM

### ISSUE THREAD

**Issue by Creddieboy** [VladimirSFilippov/node-red-contrib-broadlink#6]
![broadlink error log](https://user-images.githubusercontent.com/13499977/36782956-326b093c-1cad-11e8-9509-72942be4b4bd.jpg)
Unable to get NPM install. Issue with crypto.

**Comment by mlfunston** [comment]
Looks like just warnings. Should still work. I'm using the same version on a PI. See if it's available in the palette in node-red or restart it and try.

**Comment by Creddieboy** [comment]
Dear All,
Following an Update / upgrade on a subsequent shutdown the nodes have appeared.
Thanks to everyone for their input and assistance.
Regards,
Craig Rosier CR Developments Consulting Services
Home Phone: +66860389110CallSend SMSAdd to SkypeYou'll need Skype CreditFree via Skype 

    On Wednesday, February 28, 2018, 6:35:14 PM GMT+7, mlfunston <notifications@github.com> wrote:  
 
 
Looks like just warnings. Should still work. I'm using the same version on a PI. See if it's available in the palette in node-red or restart it and try.

**Comment by Creddieboy** [comment]
All,

 After some reinforcement from mlfunston. I performed an upgrade / update and my nodes appeared.

Thank you to everyone that provided support or advice.
